services:
  orderdispatcher:
    image: htotapally/orderdispatcher
    volumes:
           - ./orderdispatcher/dispconf.conf:/config/dispconf.conf           
  orderstatusupdater:
    image: htotapally/orderstatusupdater
    volumes:
           - ./orderstatusupdater/dispconf.conf:/config/dispconf.conf            
  
