services:
  haproxy:
    image: htotapally/haproxy
    container_name: haproxy
    ports:
      - "${haproxysrc}:${haproxydst}"
      - "${haproxyadminsrc}:${haproxyadminsrc}"
  webfrontend:
    image: htotapally/sml-apach2
    container_name: sml-apache2
    ports:
      - "${webfrontendsrc}:${webfrontenddst}"      
  reportsvc:
    image: htotapally/reportsvc
    container_name: reportsvc
    ports:
      - "${reportsvcsrc}:${reportsvcdst}"
  productsvc:
    image: htotapally/productapi
    container_name: productsvc
    ports:
      - "${productsvcsrc}:${productsvcdst}"
  ordersvc:
    image: htotapally/storovapi
    container_name: ordersvc
    ports:
      - "${ordersvcsrc}:${ordersvcdst}"
