volumes:
     postgres_data:
     solr:
services:
  haproxy:
    image: htotapally/haproxy
    container_name: haproxy
    ports:
      - "${haproxysrc}:${haproxydst}"
      - "${haproxyadminsrc}:${haproxyadminsrc}"
  webfrontend:
    image: htotapally/sml-apach2
    container_name: sml-apach2
    ports:
      - "${webfrontendsrc}:${webfrontenddst}"      
  productservice:
    image: htotapally/prodprovider
    container_name: prodprovider
    ports:
      - "${productservicesrc}:${productservicedst}"
  orderservice:
    image: htotapally/orderservice
    container_name: orderservice
    ports:
      - "${orderservicesrc}:${orderservicedst}"
  solr:
    image: htotapally/smlsolr
    container_name: smlsolr2
    volumes:
      - solr:/var/solr
    ports:
      - "${solrhost}:${solrdest}"
