volumes:
     postgres_data:
services:
  haproxy:
    image: htotapally/haproxy
    ports:
      - "${haproxysrc}:${haproxydst}"
      - "${haproxyadminsrc}:${haproxyadminsrc}"
  webfrontend:
    image: htotapally/sml-apach2
    ports:
      - "${webfrontendsrc}:${webfrontenddst}"      
  productservice:
    image: htotapally/prodprovider
    ports:
      - "${productservicesrc}:${productservicedst}"
  postgres:
    image: htotapally/sml-postgres-db
    container_name: postgres
    network_mode: "host"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data    
  orderservice:
    image: htotapally/orderservice
    ports:
      - "${orderservicesrc}:${orderservicedst}"
