services:
  haproxy:
    image: htotapally/haproxy
    ports:
      - "${haproxysrc}:${haproxydst}"
      - "${haproxyadminsrc}:${haproxyadminsrc}"
  webfrontend:
    image: htotapally/sml-apach2
    ports:
      - "${webfrontendsrc}:${webfrontenddst}"      
  productservice:
    image: htotapally/prodprovider
    ports:
      - "${productservicesrc}:${productservicedst}"
  orderservice:
    image: htotapally/orderservice
    ports:
      - "${orderservicesrc}:${orderservicedst}"
