volumes:
  solr:
  pgdata:
services:
  haproxy:
    image: htotapally/haproxy
    container_name: haproxy
    ports:
      - "${haproxysrc}:${haproxydst}"
      - "${haproxyadminsrc}:${haproxyadminsrc}"
  webfrontend:
    image: htotapally/sml-apache2
    container_name: sml-apache2
    ports:
      - "${webfrontendsrc}:${webfrontenddst}"      
  reportsvc:
    image: htotapally/reportsvc
    container_name: reportsvc
    ports:
      - "${reportsvcsrc}:${reportsvcdst}"
  productsvc:
    image: htotapally/productapi
    container_name: productsvc
    ports:
      - "${productsvcsrc}:${productsvcdst}"
  ordersvc:
    image: htotapally/storovapi
    container_name: ordersvc
    ports:
      - "${ordersvcsrc}:${ordersvcdst}"
  solr:
    image: htotapally/smlsolr
    container_name: smlsolr
    volumes:
      - solr:/var/solr
    ports:
      - "${solrhost}:${solrdest}"
  postgres:
    image: htotapally/sml-postgres-db
    container_name: smlpostgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${postgressrc}:${postgresdest}"
