version: "3.8"
services:
  haproxy:
    image: htotapally/haproxy
    ports:
      - "80:80"
      - "8404:8404"
  productservice:
    image: htotapally/prodprovider
    ports:
      - "8080:8080"
  orderservice:
    image: htotapally/orderservice
    ports:
      - "8090:8090"
