services:
  haproxy:
    image: htotapally/haproxy
    ports:
      - "${haproxysrc}:${haproxydst}"
      - "${haproxyadminsrc}:${haproxyadminsrc}"
    volumes:
           - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
  webfrontend:
    image: htotapally/sml-apach2
    ports:
      - "${webfrontendsrc}:${webfrontenddst}"    
